name: Build ISO

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libbsd-dev pkg-config openjdk-8-jdk-headless openjdk-11-jdk-headless

    - name: Softlink directories
      run: |
        ln -s /usr/lib/jvm/java-8-openjdk-amd64 host/jdk8
        ln -s /usr/lib/jvm/java-11-openjdk-amd64 host/jdk11

    - name: Make
      run: |
        make -C host/src/makefs_termux
        make -C host/src/makefs_termux install DESTDIR=$PWD/host
        make -C target
        make -C samples/helloworld
        make -C samples/ps5-app0-filedump
        make -C samples/ps5-sandbox-filedump
        make -C samples/ps5-invoke-native
        make -C samples/ps5-lua-server
        make -C samples/ps5-kernel-data-dump
        make -C samples/ps5-jar-loader
        make -C samples/ps5-elf-loader
        make -C samples/ps5-elf-loader/payloads
        make -C samples/ps5-payload-loader
        make -C samples/ps5-payload-loader/payloads/elf
        make -C samples/ps5-payload-loader/payloads/jar

    - name: Upload ps5-payload-loader artifact
      uses: actions/upload-artifact@v3
      with:
        name: ps5-payload-loader
        path: |
          samples/ps5-payload-loader/*.iso
          samples/ps5-payload-loader/payloads/elf/*.elf
          samples/ps5-payload-loader/payloads/jar/*.jar
          samples/ps5-payload-loader/payloads/lua/*.lua

    - name: Upload ps5-elf-loader artifact
      uses: actions/upload-artifact@v3
      with:
        name: ps5-elf-loader
        path: |
          samples/ps5-elf-loader/*.iso
          samples/ps5-elf-loader/payloads/*.elf

    - name: Upload ps5-jar-loader artifact
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-jar-loader/*.iso
        name: ps5-jar-loader

    - name: Upload ps5-kernel-data-dump artifact
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-kernel-data-dump/*.iso
        name: ps5-kernel-data-dump

    - name: Upload ps5-lua-server artifact
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-lua-server/*.iso
        name: ps5-lua-server

    - name: Upload ps5-invoke-native artifact
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-invoke-native/*.iso
        name: ps5-invoke-native

    - name: Upload ps5-sandbox-filedump artifact
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-sandbox-filedump/*.iso
        name: ps5-sandbox-filedump

    - name: Upload ps5-app0-filedump
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-app0-filedump/*.iso
        name: ps5-app0-filedump

    - name: Upload helloworld
      uses: actions/upload-artifact@v3
      with:
        path: samples/helloworld/*.iso
        name: helloworld
